/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EchipamentPlajaDTO model module.
 * @module model/EchipamentPlajaDTO
 * @version 1.0
 */
class EchipamentPlajaDTO {
    /**
     * Constructs a new <code>EchipamentPlajaDTO</code>.
     * @alias module:model/EchipamentPlajaDTO
     */
    constructor() { 
        
        EchipamentPlajaDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EchipamentPlajaDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EchipamentPlajaDTO} obj Optional instance to populate.
     * @return {module:model/EchipamentPlajaDTO} The populated <code>EchipamentPlajaDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EchipamentPlajaDTO();

            if (data.hasOwnProperty('activ')) {
                obj['activ'] = ApiClient.convertToType(data['activ'], 'Boolean');
            }
            if (data.hasOwnProperty('denumire')) {
                obj['denumire'] = ApiClient.convertToType(data['denumire'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('plajaDenumire')) {
                obj['plajaDenumire'] = ApiClient.convertToType(data['plajaDenumire'], 'String');
            }
            if (data.hasOwnProperty('plajaId')) {
                obj['plajaId'] = ApiClient.convertToType(data['plajaId'], 'Number');
            }
            if (data.hasOwnProperty('pozitieColoana')) {
                obj['pozitieColoana'] = ApiClient.convertToType(data['pozitieColoana'], 'Number');
            }
            if (data.hasOwnProperty('pozitieLinie')) {
                obj['pozitieLinie'] = ApiClient.convertToType(data['pozitieLinie'], 'Number');
            }
            if (data.hasOwnProperty('pretCurent')) {
                obj['pretCurent'] = ApiClient.convertToType(data['pretCurent'], 'Number');
            }
            if (data.hasOwnProperty('stareEchipamentDenumire')) {
                obj['stareEchipamentDenumire'] = ApiClient.convertToType(data['stareEchipamentDenumire'], 'String');
            }
            if (data.hasOwnProperty('stareEchipamentId')) {
                obj['stareEchipamentId'] = ApiClient.convertToType(data['stareEchipamentId'], 'Number');
            }
            if (data.hasOwnProperty('tipEchipamentDenumire')) {
                obj['tipEchipamentDenumire'] = ApiClient.convertToType(data['tipEchipamentDenumire'], 'String');
            }
            if (data.hasOwnProperty('tipEchipamentId')) {
                obj['tipEchipamentId'] = ApiClient.convertToType(data['tipEchipamentId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EchipamentPlajaDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EchipamentPlajaDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['denumire'] && !(typeof data['denumire'] === 'string' || data['denumire'] instanceof String)) {
            throw new Error("Expected the field `denumire` to be a primitive type in the JSON string but got " + data['denumire']);
        }
        // ensure the json data is a string
        if (data['plajaDenumire'] && !(typeof data['plajaDenumire'] === 'string' || data['plajaDenumire'] instanceof String)) {
            throw new Error("Expected the field `plajaDenumire` to be a primitive type in the JSON string but got " + data['plajaDenumire']);
        }
        // ensure the json data is a string
        if (data['stareEchipamentDenumire'] && !(typeof data['stareEchipamentDenumire'] === 'string' || data['stareEchipamentDenumire'] instanceof String)) {
            throw new Error("Expected the field `stareEchipamentDenumire` to be a primitive type in the JSON string but got " + data['stareEchipamentDenumire']);
        }
        // ensure the json data is a string
        if (data['tipEchipamentDenumire'] && !(typeof data['tipEchipamentDenumire'] === 'string' || data['tipEchipamentDenumire'] instanceof String)) {
            throw new Error("Expected the field `tipEchipamentDenumire` to be a primitive type in the JSON string but got " + data['tipEchipamentDenumire']);
        }

        return true;
    }


}



/**
 * @member {Boolean} activ
 */
EchipamentPlajaDTO.prototype['activ'] = undefined;

/**
 * @member {String} denumire
 */
EchipamentPlajaDTO.prototype['denumire'] = undefined;

/**
 * @member {Number} id
 */
EchipamentPlajaDTO.prototype['id'] = undefined;

/**
 * @member {String} plajaDenumire
 */
EchipamentPlajaDTO.prototype['plajaDenumire'] = undefined;

/**
 * @member {Number} plajaId
 */
EchipamentPlajaDTO.prototype['plajaId'] = undefined;

/**
 * @member {Number} pozitieColoana
 */
EchipamentPlajaDTO.prototype['pozitieColoana'] = undefined;

/**
 * @member {Number} pozitieLinie
 */
EchipamentPlajaDTO.prototype['pozitieLinie'] = undefined;

/**
 * @member {Number} pretCurent
 */
EchipamentPlajaDTO.prototype['pretCurent'] = undefined;

/**
 * @member {String} stareEchipamentDenumire
 */
EchipamentPlajaDTO.prototype['stareEchipamentDenumire'] = undefined;

/**
 * @member {Number} stareEchipamentId
 */
EchipamentPlajaDTO.prototype['stareEchipamentId'] = undefined;

/**
 * @member {String} tipEchipamentDenumire
 */
EchipamentPlajaDTO.prototype['tipEchipamentDenumire'] = undefined;

/**
 * @member {Number} tipEchipamentId
 */
EchipamentPlajaDTO.prototype['tipEchipamentId'] = undefined;






export default EchipamentPlajaDTO;

