/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileDb model module.
 * @module model/FileDb
 * @version 1.0
 */
class FileDb {
    /**
     * Constructs a new <code>FileDb</code>.
     * @alias module:model/FileDb
     */
    constructor() { 
        
        FileDb.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FileDb</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileDb} obj Optional instance to populate.
     * @return {module:model/FileDb} The populated <code>FileDb</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileDb();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FileDb</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FileDb</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {Blob} data
 */
FileDb.prototype['data'] = undefined;

/**
 * @member {Number} id
 */
FileDb.prototype['id'] = undefined;

/**
 * @member {String} name
 */
FileDb.prototype['name'] = undefined;

/**
 * @member {module:model/FileDb.TypeEnum} type
 */
FileDb.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
FileDb['TypeEnum'] = {

    /**
     * value: "IMAGE_JPEG"
     * @const
     */
    "IMAGE_JPEG": "IMAGE_JPEG",

    /**
     * value: "IMAGE_PNG"
     * @const
     */
    "IMAGE_PNG": "IMAGE_PNG"
};



export default FileDb;

