/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FirmaDTO model module.
 * @module model/FirmaDTO
 * @version 1.0
 */
class FirmaDTO {
    /**
     * Constructs a new <code>FirmaDTO</code>.
     * @alias module:model/FirmaDTO
     */
    constructor() { 
        
        FirmaDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FirmaDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FirmaDTO} obj Optional instance to populate.
     * @return {module:model/FirmaDTO} The populated <code>FirmaDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FirmaDTO();

            if (data.hasOwnProperty('activ')) {
                obj['activ'] = ApiClient.convertToType(data['activ'], 'Boolean');
            }
            if (data.hasOwnProperty('adresa')) {
                obj['adresa'] = ApiClient.convertToType(data['adresa'], 'String');
            }
            if (data.hasOwnProperty('cui')) {
                obj['cui'] = ApiClient.convertToType(data['cui'], 'String');
            }
            if (data.hasOwnProperty('denumire')) {
                obj['denumire'] = ApiClient.convertToType(data['denumire'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('telefon')) {
                obj['telefon'] = ApiClient.convertToType(data['telefon'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FirmaDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FirmaDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['adresa'] && !(typeof data['adresa'] === 'string' || data['adresa'] instanceof String)) {
            throw new Error("Expected the field `adresa` to be a primitive type in the JSON string but got " + data['adresa']);
        }
        // ensure the json data is a string
        if (data['cui'] && !(typeof data['cui'] === 'string' || data['cui'] instanceof String)) {
            throw new Error("Expected the field `cui` to be a primitive type in the JSON string but got " + data['cui']);
        }
        // ensure the json data is a string
        if (data['denumire'] && !(typeof data['denumire'] === 'string' || data['denumire'] instanceof String)) {
            throw new Error("Expected the field `denumire` to be a primitive type in the JSON string but got " + data['denumire']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['telefon'] && !(typeof data['telefon'] === 'string' || data['telefon'] instanceof String)) {
            throw new Error("Expected the field `telefon` to be a primitive type in the JSON string but got " + data['telefon']);
        }

        return true;
    }


}



/**
 * @member {Boolean} activ
 */
FirmaDTO.prototype['activ'] = undefined;

/**
 * @member {String} adresa
 */
FirmaDTO.prototype['adresa'] = undefined;

/**
 * @member {String} cui
 */
FirmaDTO.prototype['cui'] = undefined;

/**
 * @member {String} denumire
 */
FirmaDTO.prototype['denumire'] = undefined;

/**
 * @member {String} email
 */
FirmaDTO.prototype['email'] = undefined;

/**
 * @member {String} telefon
 */
FirmaDTO.prototype['telefon'] = undefined;






export default FirmaDTO;

