/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The O2AuthInfoDto model module.
 * @module model/O2AuthInfoDto
 * @version 1.0
 */
class O2AuthInfoDto {
    /**
     * Constructs a new <code>O2AuthInfoDto</code>.
     * @alias module:model/O2AuthInfoDto
     */
    constructor() { 
        
        O2AuthInfoDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>O2AuthInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/O2AuthInfoDto} obj Optional instance to populate.
     * @return {module:model/O2AuthInfoDto} The populated <code>O2AuthInfoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new O2AuthInfoDto();

            if (data.hasOwnProperty('needToSetPassword')) {
                obj['needToSetPassword'] = ApiClient.convertToType(data['needToSetPassword'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>O2AuthInfoDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>O2AuthInfoDto</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} needToSetPassword
 */
O2AuthInfoDto.prototype['needToSetPassword'] = undefined;






export default O2AuthInfoDto;

