/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Firma from './Firma';
import Statiune from './Statiune';

/**
 * The Plaja model module.
 * @module model/Plaja
 * @version 1.0
 */
class Plaja {
    /**
     * Constructs a new <code>Plaja</code>.
     * @alias module:model/Plaja
     */
    constructor() { 
        
        Plaja.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Plaja</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Plaja} obj Optional instance to populate.
     * @return {module:model/Plaja} The populated <code>Plaja</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Plaja();

            if (data.hasOwnProperty('activ')) {
                obj['activ'] = ApiClient.convertToType(data['activ'], 'Boolean');
            }
            if (data.hasOwnProperty('denumire')) {
                obj['denumire'] = ApiClient.convertToType(data['denumire'], 'String');
            }
            if (data.hasOwnProperty('descriere')) {
                obj['descriere'] = ApiClient.convertToType(data['descriere'], 'String');
            }
            if (data.hasOwnProperty('detaliiWeb')) {
                obj['detaliiWeb'] = ApiClient.convertToType(data['detaliiWeb'], Object);
            }
            if (data.hasOwnProperty('firma')) {
                obj['firma'] = Firma.constructFromObject(data['firma']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('numarSezlonguri')) {
                obj['numarSezlonguri'] = ApiClient.convertToType(data['numarSezlonguri'], 'Number');
            }
            if (data.hasOwnProperty('statiune')) {
                obj['statiune'] = Statiune.constructFromObject(data['statiune']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Plaja</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Plaja</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['denumire'] && !(typeof data['denumire'] === 'string' || data['denumire'] instanceof String)) {
            throw new Error("Expected the field `denumire` to be a primitive type in the JSON string but got " + data['denumire']);
        }
        // ensure the json data is a string
        if (data['descriere'] && !(typeof data['descriere'] === 'string' || data['descriere'] instanceof String)) {
            throw new Error("Expected the field `descriere` to be a primitive type in the JSON string but got " + data['descriere']);
        }
        // validate the optional field `firma`
        if (data['firma']) { // data not null
          Firma.validateJSON(data['firma']);
        }
        // validate the optional field `statiune`
        if (data['statiune']) { // data not null
          Statiune.validateJSON(data['statiune']);
        }

        return true;
    }


}



/**
 * @member {Boolean} activ
 */
Plaja.prototype['activ'] = undefined;

/**
 * @member {String} denumire
 */
Plaja.prototype['denumire'] = undefined;

/**
 * @member {String} descriere
 */
Plaja.prototype['descriere'] = undefined;

/**
 * @member {Object} detaliiWeb
 */
Plaja.prototype['detaliiWeb'] = undefined;

/**
 * @member {module:model/Firma} firma
 */
Plaja.prototype['firma'] = undefined;

/**
 * @member {Number} id
 */
Plaja.prototype['id'] = undefined;

/**
 * @member {Number} numarSezlonguri
 */
Plaja.prototype['numarSezlonguri'] = undefined;

/**
 * @member {module:model/Statiune} statiune
 */
Plaja.prototype['statiune'] = undefined;






export default Plaja;

