/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PretDTO model module.
 * @module model/PretDTO
 * @version 1.0
 */
class PretDTO {
    /**
     * Constructs a new <code>PretDTO</code>.
     * @alias module:model/PretDTO
     */
    constructor() { 
        
        PretDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PretDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PretDTO} obj Optional instance to populate.
     * @return {module:model/PretDTO} The populated <code>PretDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PretDTO();

            if (data.hasOwnProperty('dataOra')) {
                obj['dataOra'] = ApiClient.convertToType(data['dataOra'], 'Date');
            }
            if (data.hasOwnProperty('echipamentPlajaId')) {
                obj['echipamentPlajaId'] = ApiClient.convertToType(data['echipamentPlajaId'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('valoare')) {
                obj['valoare'] = ApiClient.convertToType(data['valoare'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PretDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PretDTO</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Date} dataOra
 */
PretDTO.prototype['dataOra'] = undefined;

/**
 * @member {Number} echipamentPlajaId
 */
PretDTO.prototype['echipamentPlajaId'] = undefined;

/**
 * @member {Number} id
 */
PretDTO.prototype['id'] = undefined;

/**
 * @member {Number} valoare
 */
PretDTO.prototype['valoare'] = undefined;






export default PretDTO;

