/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StareRezervare from './StareRezervare';
import User from './User';

/**
 * The Rezervare model module.
 * @module model/Rezervare
 * @version 1.0
 */
class Rezervare {
    /**
     * Constructs a new <code>Rezervare</code>.
     * @alias module:model/Rezervare
     */
    constructor() { 
        
        Rezervare.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Rezervare</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Rezervare} obj Optional instance to populate.
     * @return {module:model/Rezervare} The populated <code>Rezervare</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Rezervare();

            if (data.hasOwnProperty('codRezervare')) {
                obj['codRezervare'] = ApiClient.convertToType(data['codRezervare'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('stareRezervare')) {
                obj['stareRezervare'] = StareRezervare.constructFromObject(data['stareRezervare']);
            }
            if (data.hasOwnProperty('utilizator')) {
                obj['utilizator'] = User.constructFromObject(data['utilizator']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Rezervare</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Rezervare</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['codRezervare'] && !(typeof data['codRezervare'] === 'string' || data['codRezervare'] instanceof String)) {
            throw new Error("Expected the field `codRezervare` to be a primitive type in the JSON string but got " + data['codRezervare']);
        }
        // validate the optional field `stareRezervare`
        if (data['stareRezervare']) { // data not null
          StareRezervare.validateJSON(data['stareRezervare']);
        }
        // validate the optional field `utilizator`
        if (data['utilizator']) { // data not null
          User.validateJSON(data['utilizator']);
        }

        return true;
    }


}



/**
 * @member {String} codRezervare
 */
Rezervare.prototype['codRezervare'] = undefined;

/**
 * @member {Date} createdAt
 */
Rezervare.prototype['createdAt'] = undefined;

/**
 * @member {Number} id
 */
Rezervare.prototype['id'] = undefined;

/**
 * @member {module:model/StareRezervare} stareRezervare
 */
Rezervare.prototype['stareRezervare'] = undefined;

/**
 * @member {module:model/User} utilizator
 */
Rezervare.prototype['utilizator'] = undefined;






export default Rezervare;

