/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TipEchipamentPlaja model module.
 * @module model/TipEchipamentPlaja
 * @version 1.0
 */
class TipEchipamentPlaja {
    /**
     * Constructs a new <code>TipEchipamentPlaja</code>.
     * @alias module:model/TipEchipamentPlaja
     * @param denumire {String} 
     */
    constructor(denumire) { 
        
        TipEchipamentPlaja.initialize(this, denumire);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, denumire) { 
        obj['denumire'] = denumire;
    }

    /**
     * Constructs a <code>TipEchipamentPlaja</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TipEchipamentPlaja} obj Optional instance to populate.
     * @return {module:model/TipEchipamentPlaja} The populated <code>TipEchipamentPlaja</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TipEchipamentPlaja();

            if (data.hasOwnProperty('dataOra')) {
                obj['dataOra'] = ApiClient.convertToType(data['dataOra'], 'Date');
            }
            if (data.hasOwnProperty('denumire')) {
                obj['denumire'] = ApiClient.convertToType(data['denumire'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TipEchipamentPlaja</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TipEchipamentPlaja</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TipEchipamentPlaja.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['denumire'] && !(typeof data['denumire'] === 'string' || data['denumire'] instanceof String)) {
            throw new Error("Expected the field `denumire` to be a primitive type in the JSON string but got " + data['denumire']);
        }

        return true;
    }


}

TipEchipamentPlaja.RequiredProperties = ["denumire"];

/**
 * @member {Date} dataOra
 */
TipEchipamentPlaja.prototype['dataOra'] = undefined;

/**
 * @member {String} denumire
 */
TipEchipamentPlaja.prototype['denumire'] = undefined;

/**
 * @member {Number} id
 */
TipEchipamentPlaja.prototype['id'] = undefined;






export default TipEchipamentPlaja;

