/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TipEchipamentPlajaDTO model module.
 * @module model/TipEchipamentPlajaDTO
 * @version 1.0
 */
class TipEchipamentPlajaDTO {
    /**
     * Constructs a new <code>TipEchipamentPlajaDTO</code>.
     * @alias module:model/TipEchipamentPlajaDTO
     */
    constructor() { 
        
        TipEchipamentPlajaDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TipEchipamentPlajaDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TipEchipamentPlajaDTO} obj Optional instance to populate.
     * @return {module:model/TipEchipamentPlajaDTO} The populated <code>TipEchipamentPlajaDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TipEchipamentPlajaDTO();

            if (data.hasOwnProperty('activ')) {
                obj['activ'] = ApiClient.convertToType(data['activ'], 'Boolean');
            }
            if (data.hasOwnProperty('denumire')) {
                obj['denumire'] = ApiClient.convertToType(data['denumire'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TipEchipamentPlajaDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TipEchipamentPlajaDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['denumire'] && !(typeof data['denumire'] === 'string' || data['denumire'] instanceof String)) {
            throw new Error("Expected the field `denumire` to be a primitive type in the JSON string but got " + data['denumire']);
        }

        return true;
    }


}



/**
 * @member {Boolean} activ
 */
TipEchipamentPlajaDTO.prototype['activ'] = undefined;

/**
 * @member {String} denumire
 */
TipEchipamentPlajaDTO.prototype['denumire'] = undefined;






export default TipEchipamentPlajaDTO;

