/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The TwoFactorRecoveryCode model module.
 * @module model/TwoFactorRecoveryCode
 * @version 1.0
 */
class TwoFactorRecoveryCode {
    /**
     * Constructs a new <code>TwoFactorRecoveryCode</code>.
     * @alias module:model/TwoFactorRecoveryCode
     */
    constructor() { 
        
        TwoFactorRecoveryCode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorRecoveryCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorRecoveryCode} obj Optional instance to populate.
     * @return {module:model/TwoFactorRecoveryCode} The populated <code>TwoFactorRecoveryCode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorRecoveryCode();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('recoveryCode')) {
                obj['recoveryCode'] = ApiClient.convertToType(data['recoveryCode'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TwoFactorRecoveryCode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TwoFactorRecoveryCode</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['recoveryCode'] && !(typeof data['recoveryCode'] === 'string' || data['recoveryCode'] instanceof String)) {
            throw new Error("Expected the field `recoveryCode` to be a primitive type in the JSON string but got " + data['recoveryCode']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          User.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TwoFactorRecoveryCode.prototype['id'] = undefined;

/**
 * @member {String} recoveryCode
 */
TwoFactorRecoveryCode.prototype['recoveryCode'] = undefined;

/**
 * @member {module:model/User} user
 */
TwoFactorRecoveryCode.prototype['user'] = undefined;

/**
 * @member {Number} userId
 */
TwoFactorRecoveryCode.prototype['userId'] = undefined;






export default TwoFactorRecoveryCode;

