/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorDto model module.
 * @module model/TwoFactorDto
 * @version 1.0
 */
class TwoFactorDto {
    /**
     * Constructs a new <code>TwoFactorDto</code>.
     * @alias module:model/TwoFactorDto
     */
    constructor() { 
        
        TwoFactorDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorDto} obj Optional instance to populate.
     * @return {module:model/TwoFactorDto} The populated <code>TwoFactorDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorDto();

            if (data.hasOwnProperty('verificationCodes')) {
                obj['verificationCodes'] = ApiClient.convertToType(data['verificationCodes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TwoFactorDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TwoFactorDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['verificationCodes'])) {
            throw new Error("Expected the field `verificationCodes` to be an array in the JSON data but got " + data['verificationCodes']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} verificationCodes
 */
TwoFactorDto.prototype['verificationCodes'] = undefined;






export default TwoFactorDto;

