/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TwoFactorSetupDto model module.
 * @module model/TwoFactorSetupDto
 * @version 1.0
 */
class TwoFactorSetupDto {
    /**
     * Constructs a new <code>TwoFactorSetupDto</code>.
     * @alias module:model/TwoFactorSetupDto
     */
    constructor() { 
        
        TwoFactorSetupDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TwoFactorSetupDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TwoFactorSetupDto} obj Optional instance to populate.
     * @return {module:model/TwoFactorSetupDto} The populated <code>TwoFactorSetupDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TwoFactorSetupDto();

            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('qrData')) {
                obj['qrData'] = ApiClient.convertToType(data['qrData'], 'Blob');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TwoFactorSetupDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TwoFactorSetupDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }

        return true;
    }


}



/**
 * @member {String} mimeType
 */
TwoFactorSetupDto.prototype['mimeType'] = undefined;

/**
 * @member {Blob} qrData
 */
TwoFactorSetupDto.prototype['qrData'] = undefined;






export default TwoFactorSetupDto;

