/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileDbDto from './FileDbDto';
import O2AuthInfoDto from './O2AuthInfoDto';

/**
 * The UserDto model module.
 * @module model/UserDto
 * @version 1.0
 */
class UserDto {
    /**
     * Constructs a new <code>UserDto</code>.
     * @alias module:model/UserDto
     */
    constructor() { 
        
        UserDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDto} obj Optional instance to populate.
     * @return {module:model/UserDto} The populated <code>UserDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDto();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('o2AuthInfo')) {
                obj['o2AuthInfo'] = O2AuthInfoDto.constructFromObject(data['o2AuthInfo']);
            }
            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = FileDbDto.constructFromObject(data['profileImage']);
            }
            if (data.hasOwnProperty('twoFactorEnabled')) {
                obj['twoFactorEnabled'] = ApiClient.convertToType(data['twoFactorEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `o2AuthInfo`
        if (data['o2AuthInfo']) { // data not null
          O2AuthInfoDto.validateJSON(data['o2AuthInfo']);
        }
        // validate the optional field `profileImage`
        if (data['profileImage']) { // data not null
          FileDbDto.validateJSON(data['profileImage']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
UserDto.prototype['email'] = undefined;

/**
 * @member {String} name
 */
UserDto.prototype['name'] = undefined;

/**
 * @member {module:model/O2AuthInfoDto} o2AuthInfo
 */
UserDto.prototype['o2AuthInfo'] = undefined;

/**
 * @member {module:model/FileDbDto} profileImage
 */
UserDto.prototype['profileImage'] = undefined;

/**
 * @member {Boolean} twoFactorEnabled
 */
UserDto.prototype['twoFactorEnabled'] = undefined;






export default UserDto;

