/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.EchipamentPlajaDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EchipamentPlajaDTO', function() {
    it('should create an instance of EchipamentPlajaDTO', function() {
      // uncomment below and update the code to test EchipamentPlajaDTO
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be.a(ApiDocumentation.EchipamentPlajaDTO);
    });

    it('should have the property activ (base name: "activ")', function() {
      // uncomment below and update the code to test the property activ
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property denumire (base name: "denumire")', function() {
      // uncomment below and update the code to test the property denumire
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property plajaDenumire (base name: "plajaDenumire")', function() {
      // uncomment below and update the code to test the property plajaDenumire
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property plajaId (base name: "plajaId")', function() {
      // uncomment below and update the code to test the property plajaId
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property pozitieColoana (base name: "pozitieColoana")', function() {
      // uncomment below and update the code to test the property pozitieColoana
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property pozitieLinie (base name: "pozitieLinie")', function() {
      // uncomment below and update the code to test the property pozitieLinie
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property pretCurent (base name: "pretCurent")', function() {
      // uncomment below and update the code to test the property pretCurent
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property stareEchipamentDenumire (base name: "stareEchipamentDenumire")', function() {
      // uncomment below and update the code to test the property stareEchipamentDenumire
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property stareEchipamentId (base name: "stareEchipamentId")', function() {
      // uncomment below and update the code to test the property stareEchipamentId
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property tipEchipamentDenumire (base name: "tipEchipamentDenumire")', function() {
      // uncomment below and update the code to test the property tipEchipamentDenumire
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property tipEchipamentId (base name: "tipEchipamentId")', function() {
      // uncomment below and update the code to test the property tipEchipamentId
      //var instance = new ApiDocumentation.EchipamentPlajaDTO();
      //expect(instance).to.be();
    });

  });

}));
