/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.FirmaDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FirmaDTO', function() {
    it('should create an instance of FirmaDTO', function() {
      // uncomment below and update the code to test FirmaDTO
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be.a(ApiDocumentation.FirmaDTO);
    });

    it('should have the property activ (base name: "activ")', function() {
      // uncomment below and update the code to test the property activ
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

    it('should have the property adresa (base name: "adresa")', function() {
      // uncomment below and update the code to test the property adresa
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

    it('should have the property cui (base name: "cui")', function() {
      // uncomment below and update the code to test the property cui
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

    it('should have the property denumire (base name: "denumire")', function() {
      // uncomment below and update the code to test the property denumire
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

    it('should have the property telefon (base name: "telefon")', function() {
      // uncomment below and update the code to test the property telefon
      //var instance = new ApiDocumentation.FirmaDTO();
      //expect(instance).to.be();
    });

  });

}));
