/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.PlajaDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlajaDTO', function() {
    it('should create an instance of PlajaDTO', function() {
      // uncomment below and update the code to test PlajaDTO
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be.a(ApiDocumentation.PlajaDTO);
    });

    it('should have the property activ (base name: "activ")', function() {
      // uncomment below and update the code to test the property activ
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property denumire (base name: "denumire")', function() {
      // uncomment below and update the code to test the property denumire
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property descriere (base name: "descriere")', function() {
      // uncomment below and update the code to test the property descriere
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property firmaId (base name: "firmaId")', function() {
      // uncomment below and update the code to test the property firmaId
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property numarSezlonguri (base name: "numarSezlonguri")', function() {
      // uncomment below and update the code to test the property numarSezlonguri
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

    it('should have the property statiuneId (base name: "statiuneId")', function() {
      // uncomment below and update the code to test the property statiuneId
      //var instance = new ApiDocumentation.PlajaDTO();
      //expect(instance).to.be();
    });

  });

}));
