/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.Poza();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Poza', function() {
    it('should create an instance of Poza', function() {
      // uncomment below and update the code to test Poza
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be.a(ApiDocumentation.Poza);
    });

    it('should have the property caleImagine (base name: "caleImagine")', function() {
      // uncomment below and update the code to test the property caleImagine
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be();
    });

    it('should have the property ordine (base name: "ordine")', function() {
      // uncomment below and update the code to test the property ordine
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be();
    });

    it('should have the property plajaId (base name: "plajaId")', function() {
      // uncomment below and update the code to test the property plajaId
      //var instance = new ApiDocumentation.Poza();
      //expect(instance).to.be();
    });

  });

}));
