/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be.a(ApiDocumentation.User);
    });

    it('should have the property authProvider (base name: "authProvider")', function() {
      // uncomment below and update the code to test the property authProvider
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property emailVerified (base name: "emailVerified")', function() {
      // uncomment below and update the code to test the property emailVerified
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property jwtTokens (base name: "jwtTokens")', function() {
      // uncomment below and update the code to test the property jwtTokens
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property profileImage (base name: "profileImage")', function() {
      // uncomment below and update the code to test the property profileImage
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property providerId (base name: "providerId")', function() {
      // uncomment below and update the code to test the property providerId
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property requestedNewEmail (base name: "requestedNewEmail")', function() {
      // uncomment below and update the code to test the property requestedNewEmail
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property role (base name: "role")', function() {
      // uncomment below and update the code to test the property role
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property twoFactorEnabled (base name: "twoFactorEnabled")', function() {
      // uncomment below and update the code to test the property twoFactorEnabled
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property twoFactorRecoveryCodes (base name: "twoFactorRecoveryCodes")', function() {
      // uncomment below and update the code to test the property twoFactorRecoveryCodes
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

    it('should have the property twoFactorSecret (base name: "twoFactorSecret")', function() {
      // uncomment below and update the code to test the property twoFactorSecret
      //var instance = new ApiDocumentation.User();
      //expect(instance).to.be();
    });

  });

}));
