/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthResponseDto from './model/AuthResponseDto';
import ChangePasswordDto from './model/ChangePasswordDto';
import EchipamentPlaja from './model/EchipamentPlaja';
import EchipamentPlajaDTO from './model/EchipamentPlajaDTO';
import FileDb from './model/FileDb';
import FileDbDto from './model/FileDbDto';
import Firma from './model/Firma';
import FirmaDTO from './model/FirmaDTO';
import ForgottenPasswordRequestDto from './model/ForgottenPasswordRequestDto';
import JwtToken from './model/JwtToken';
import LoginRequestDto from './model/LoginRequestDto';
import LoginVerificationRequestDto from './model/LoginVerificationRequestDto';
import ModelAndView from './model/ModelAndView';
import O2AuthInfoDto from './model/O2AuthInfoDto';
import PasswordResetRequestDto from './model/PasswordResetRequestDto';
import Plaja from './model/Plaja';
import PlajaDTO from './model/PlajaDTO';
import Poza from './model/Poza';
import Pret from './model/Pret';
import PretDTO from './model/PretDTO';
import Rezervare from './model/Rezervare';
import SignUpRequestDto from './model/SignUpRequestDto';
import StareEchipamentPlaja from './model/StareEchipamentPlaja';
import StareEchipamentPlajaDTO from './model/StareEchipamentPlajaDTO';
import StareRezervare from './model/StareRezervare';
import Statiune from './model/Statiune';
import StatiuneDTO from './model/StatiuneDTO';
import TipEchipamentPlaja from './model/TipEchipamentPlaja';
import TipEchipamentPlajaDTO from './model/TipEchipamentPlajaDTO';
import TokenAccessRequestDto from './model/TokenAccessRequestDto';
import TokenResponseDto from './model/TokenResponseDto';
import TwoFactorDto from './model/TwoFactorDto';
import TwoFactorRecoveryCode from './model/TwoFactorRecoveryCode';
import TwoFactorSetupDto from './model/TwoFactorSetupDto';
import TwoFactorVerificationRequestDto from './model/TwoFactorVerificationRequestDto';
import User from './model/User';
import UserDto from './model/UserDto';
import View from './model/View';
import AuthControllerApi from './api/AuthControllerApi';
import BasicErrorControllerApi from './api/BasicErrorControllerApi';
import EchipamentPlajaControllerApi from './api/EchipamentPlajaControllerApi';
import FirmaControllerApi from './api/FirmaControllerApi';
import PlajaControllerApi from './api/PlajaControllerApi';
import PozaControllerApi from './api/PozaControllerApi';
import RezervareControllerApi from './api/RezervareControllerApi';
import StareEchipamentPlajaControllerApi from './api/StareEchipamentPlajaControllerApi';
import StareRezervareControllerApi from './api/StareRezervareControllerApi';
import StatiuneControllerApi from './api/StatiuneControllerApi';
import TipEchipamentPlajaControllerApi from './api/TipEchipamentPlajaControllerApi';
import UserControllerApi from './api/UserControllerApi';


/**
* Api Documentation.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthResponseDto model constructor.
     * @property {module:model/AuthResponseDto}
     */
    AuthResponseDto,

    /**
     * The ChangePasswordDto model constructor.
     * @property {module:model/ChangePasswordDto}
     */
    ChangePasswordDto,

    /**
     * The EchipamentPlaja model constructor.
     * @property {module:model/EchipamentPlaja}
     */
    EchipamentPlaja,

    /**
     * The EchipamentPlajaDTO model constructor.
     * @property {module:model/EchipamentPlajaDTO}
     */
    EchipamentPlajaDTO,

    /**
     * The FileDb model constructor.
     * @property {module:model/FileDb}
     */
    FileDb,

    /**
     * The FileDbDto model constructor.
     * @property {module:model/FileDbDto}
     */
    FileDbDto,

    /**
     * The Firma model constructor.
     * @property {module:model/Firma}
     */
    Firma,

    /**
     * The FirmaDTO model constructor.
     * @property {module:model/FirmaDTO}
     */
    FirmaDTO,

    /**
     * The ForgottenPasswordRequestDto model constructor.
     * @property {module:model/ForgottenPasswordRequestDto}
     */
    ForgottenPasswordRequestDto,

    /**
     * The JwtToken model constructor.
     * @property {module:model/JwtToken}
     */
    JwtToken,

    /**
     * The LoginRequestDto model constructor.
     * @property {module:model/LoginRequestDto}
     */
    LoginRequestDto,

    /**
     * The LoginVerificationRequestDto model constructor.
     * @property {module:model/LoginVerificationRequestDto}
     */
    LoginVerificationRequestDto,

    /**
     * The ModelAndView model constructor.
     * @property {module:model/ModelAndView}
     */
    ModelAndView,

    /**
     * The O2AuthInfoDto model constructor.
     * @property {module:model/O2AuthInfoDto}
     */
    O2AuthInfoDto,

    /**
     * The PasswordResetRequestDto model constructor.
     * @property {module:model/PasswordResetRequestDto}
     */
    PasswordResetRequestDto,

    /**
     * The Plaja model constructor.
     * @property {module:model/Plaja}
     */
    Plaja,

    /**
     * The PlajaDTO model constructor.
     * @property {module:model/PlajaDTO}
     */
    PlajaDTO,

    /**
     * The Poza model constructor.
     * @property {module:model/Poza}
     */
    Poza,

    /**
     * The Pret model constructor.
     * @property {module:model/Pret}
     */
    Pret,

    /**
     * The PretDTO model constructor.
     * @property {module:model/PretDTO}
     */
    PretDTO,

    /**
     * The Rezervare model constructor.
     * @property {module:model/Rezervare}
     */
    Rezervare,

    /**
     * The SignUpRequestDto model constructor.
     * @property {module:model/SignUpRequestDto}
     */
    SignUpRequestDto,

    /**
     * The StareEchipamentPlaja model constructor.
     * @property {module:model/StareEchipamentPlaja}
     */
    StareEchipamentPlaja,

    /**
     * The StareEchipamentPlajaDTO model constructor.
     * @property {module:model/StareEchipamentPlajaDTO}
     */
    StareEchipamentPlajaDTO,

    /**
     * The StareRezervare model constructor.
     * @property {module:model/StareRezervare}
     */
    StareRezervare,

    /**
     * The Statiune model constructor.
     * @property {module:model/Statiune}
     */
    Statiune,

    /**
     * The StatiuneDTO model constructor.
     * @property {module:model/StatiuneDTO}
     */
    StatiuneDTO,

    /**
     * The TipEchipamentPlaja model constructor.
     * @property {module:model/TipEchipamentPlaja}
     */
    TipEchipamentPlaja,

    /**
     * The TipEchipamentPlajaDTO model constructor.
     * @property {module:model/TipEchipamentPlajaDTO}
     */
    TipEchipamentPlajaDTO,

    /**
     * The TokenAccessRequestDto model constructor.
     * @property {module:model/TokenAccessRequestDto}
     */
    TokenAccessRequestDto,

    /**
     * The TokenResponseDto model constructor.
     * @property {module:model/TokenResponseDto}
     */
    TokenResponseDto,

    /**
     * The TwoFactorDto model constructor.
     * @property {module:model/TwoFactorDto}
     */
    TwoFactorDto,

    /**
     * The TwoFactorRecoveryCode model constructor.
     * @property {module:model/TwoFactorRecoveryCode}
     */
    TwoFactorRecoveryCode,

    /**
     * The TwoFactorSetupDto model constructor.
     * @property {module:model/TwoFactorSetupDto}
     */
    TwoFactorSetupDto,

    /**
     * The TwoFactorVerificationRequestDto model constructor.
     * @property {module:model/TwoFactorVerificationRequestDto}
     */
    TwoFactorVerificationRequestDto,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserDto model constructor.
     * @property {module:model/UserDto}
     */
    UserDto,

    /**
     * The View model constructor.
     * @property {module:model/View}
     */
    View,

    /**
    * The AuthControllerApi service constructor.
    * @property {module:api/AuthControllerApi}
    */
    AuthControllerApi,

    /**
    * The BasicErrorControllerApi service constructor.
    * @property {module:api/BasicErrorControllerApi}
    */
    BasicErrorControllerApi,

    /**
    * The EchipamentPlajaControllerApi service constructor.
    * @property {module:api/EchipamentPlajaControllerApi}
    */
    EchipamentPlajaControllerApi,

    /**
    * The FirmaControllerApi service constructor.
    * @property {module:api/FirmaControllerApi}
    */
    FirmaControllerApi,

    /**
    * The PlajaControllerApi service constructor.
    * @property {module:api/PlajaControllerApi}
    */
    PlajaControllerApi,

    /**
    * The PozaControllerApi service constructor.
    * @property {module:api/PozaControllerApi}
    */
    PozaControllerApi,

    /**
    * The RezervareControllerApi service constructor.
    * @property {module:api/RezervareControllerApi}
    */
    RezervareControllerApi,

    /**
    * The StareEchipamentPlajaControllerApi service constructor.
    * @property {module:api/StareEchipamentPlajaControllerApi}
    */
    StareEchipamentPlajaControllerApi,

    /**
    * The StareRezervareControllerApi service constructor.
    * @property {module:api/StareRezervareControllerApi}
    */
    StareRezervareControllerApi,

    /**
    * The StatiuneControllerApi service constructor.
    * @property {module:api/StatiuneControllerApi}
    */
    StatiuneControllerApi,

    /**
    * The TipEchipamentPlajaControllerApi service constructor.
    * @property {module:api/TipEchipamentPlajaControllerApi}
    */
    TipEchipamentPlajaControllerApi,

    /**
    * The UserControllerApi service constructor.
    * @property {module:api/UserControllerApi}
    */
    UserControllerApi
};
