/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.AuthControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthControllerApi', function() {
    describe('activateUserAccountUsingPOST', function() {
      it('should call activateUserAccountUsingPOST successfully', function(done) {
        //uncomment below and update the code to test activateUserAccountUsingPOST
        //instance.activateUserAccountUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authenticateUserUsingPOST', function() {
      it('should call authenticateUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test authenticateUserUsingPOST
        //instance.authenticateUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmEmailChangeUsingPOST', function() {
      it('should call confirmEmailChangeUsingPOST successfully', function(done) {
        //uncomment below and update the code to test confirmEmailChangeUsingPOST
        //instance.confirmEmailChangeUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('forgottenPasswordUsingPOST', function() {
      it('should call forgottenPasswordUsingPOST successfully', function(done) {
        //uncomment below and update the code to test forgottenPasswordUsingPOST
        //instance.forgottenPasswordUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('loginRecoveryCodeUsingPOST', function() {
      it('should call loginRecoveryCodeUsingPOST successfully', function(done) {
        //uncomment below and update the code to test loginRecoveryCodeUsingPOST
        //instance.loginRecoveryCodeUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passwordResetUsingPOST', function() {
      it('should call passwordResetUsingPOST successfully', function(done) {
        //uncomment below and update the code to test passwordResetUsingPOST
        //instance.passwordResetUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('refreshAuthUsingGET', function() {
      it('should call refreshAuthUsingGET successfully', function(done) {
        //uncomment below and update the code to test refreshAuthUsingGET
        //instance.refreshAuthUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerUserUsingPOST', function() {
      it('should call registerUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test registerUserUsingPOST
        //instance.registerUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyLoginUsingPOST', function() {
      it('should call verifyLoginUsingPOST successfully', function(done) {
        //uncomment below and update the code to test verifyLoginUsingPOST
        //instance.verifyLoginUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
