/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.FirmaControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FirmaControllerApi', function() {
    describe('createFirmaUsingPOST', function() {
      it('should call createFirmaUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createFirmaUsingPOST
        //instance.createFirmaUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFirmaUsingDELETE', function() {
      it('should call deleteFirmaUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteFirmaUsingDELETE
        //instance.deleteFirmaUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllFirmeUsingGET', function() {
      it('should call getAllFirmeUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllFirmeUsingGET
        //instance.getAllFirmeUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFirmaByIdUsingGET', function() {
      it('should call getFirmaByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getFirmaByIdUsingGET
        //instance.getFirmaByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchFirmaUsingPATCH', function() {
      it('should call patchFirmaUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test patchFirmaUsingPATCH
        //instance.patchFirmaUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFirmaUsingPUT', function() {
      it('should call updateFirmaUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateFirmaUsingPUT
        //instance.updateFirmaUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
