/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.PlajaControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlajaControllerApi', function() {
    describe('createPlajaUsingPOST', function() {
      it('should call createPlajaUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createPlajaUsingPOST
        //instance.createPlajaUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePlajaUsingDELETE', function() {
      it('should call deletePlajaUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deletePlajaUsingDELETE
        //instance.deletePlajaUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllPlajeUsingGET', function() {
      it('should call getAllPlajeUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllPlajeUsingGET
        //instance.getAllPlajeUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlajaByIdUsingGET', function() {
      it('should call getPlajaByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPlajaByIdUsingGET
        //instance.getPlajaByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlajeByActivUsingGET', function() {
      it('should call getPlajeByActivUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPlajeByActivUsingGET
        //instance.getPlajeByActivUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlajeByStatiuneIdUsingGET', function() {
      it('should call getPlajeByStatiuneIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPlajeByStatiuneIdUsingGET
        //instance.getPlajeByStatiuneIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchPlajaUsingPATCH', function() {
      it('should call patchPlajaUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test patchPlajaUsingPATCH
        //instance.patchPlajaUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePlajaUsingPUT', function() {
      it('should call updatePlajaUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updatePlajaUsingPUT
        //instance.updatePlajaUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
