/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.PozaControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PozaControllerApi', function() {
    describe('createPozaUsingPOST', function() {
      it('should call createPozaUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createPozaUsingPOST
        //instance.createPozaUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePozaUsingDELETE', function() {
      it('should call deletePozaUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deletePozaUsingDELETE
        //instance.deletePozaUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllPozeUsingGET', function() {
      it('should call getAllPozeUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllPozeUsingGET
        //instance.getAllPozeUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPozaByIdUsingGET', function() {
      it('should call getPozaByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPozaByIdUsingGET
        //instance.getPozaByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPozeByPlajaIdUsingGET', function() {
      it('should call getPozeByPlajaIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getPozeByPlajaIdUsingGET
        //instance.getPozeByPlajaIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePozaUsingPUT', function() {
      it('should call updatePozaUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updatePozaUsingPUT
        //instance.updatePozaUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
