/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.RezervareControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RezervareControllerApi', function() {
    describe('createRezervareUsingPOST', function() {
      it('should call createRezervareUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createRezervareUsingPOST
        //instance.createRezervareUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRezervareUsingDELETE', function() {
      it('should call deleteRezervareUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteRezervareUsingDELETE
        //instance.deleteRezervareUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllRezervariUsingGET', function() {
      it('should call getAllRezervariUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllRezervariUsingGET
        //instance.getAllRezervariUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRezervareByIdUsingGET', function() {
      it('should call getRezervareByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getRezervareByIdUsingGET
        //instance.getRezervareByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRezervareUsingPUT', function() {
      it('should call updateRezervareUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateRezervareUsingPUT
        //instance.updateRezervareUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
