/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.StareEchipamentPlajaControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StareEchipamentPlajaControllerApi', function() {
    describe('actualizeazaPartialUsingPATCH', function() {
      it('should call actualizeazaPartialUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test actualizeazaPartialUsingPATCH
        //instance.actualizeazaPartialUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createStareEchipamentPlajaUsingPOST', function() {
      it('should call createStareEchipamentPlajaUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createStareEchipamentPlajaUsingPOST
        //instance.createStareEchipamentPlajaUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStareEchipamentPlajaUsingDELETE', function() {
      it('should call deleteStareEchipamentPlajaUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteStareEchipamentPlajaUsingDELETE
        //instance.deleteStareEchipamentPlajaUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllStariEchipamentePlajaUsingGET', function() {
      it('should call getAllStariEchipamentePlajaUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllStariEchipamentePlajaUsingGET
        //instance.getAllStariEchipamentePlajaUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStareEchipamentPlajaByIdUsingGET', function() {
      it('should call getStareEchipamentPlajaByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getStareEchipamentPlajaByIdUsingGET
        //instance.getStareEchipamentPlajaByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStareEchipamentPlajaUsingPUT', function() {
      it('should call updateStareEchipamentPlajaUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateStareEchipamentPlajaUsingPUT
        //instance.updateStareEchipamentPlajaUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
