/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.StatiuneControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StatiuneControllerApi', function() {
    describe('createStatiuneUsingPOST', function() {
      it('should call createStatiuneUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createStatiuneUsingPOST
        //instance.createStatiuneUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStatiuneUsingDELETE', function() {
      it('should call deleteStatiuneUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteStatiuneUsingDELETE
        //instance.deleteStatiuneUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllStatiuniUsingGET', function() {
      it('should call getAllStatiuniUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllStatiuniUsingGET
        //instance.getAllStatiuniUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStatiuneByIdUsingGET', function() {
      it('should call getStatiuneByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getStatiuneByIdUsingGET
        //instance.getStatiuneByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchStatiuneUsingPATCH', function() {
      it('should call patchStatiuneUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test patchStatiuneUsingPATCH
        //instance.patchStatiuneUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStatiuneUsingPUT', function() {
      it('should call updateStatiuneUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateStatiuneUsingPUT
        //instance.updateStatiuneUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
