/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.TipEchipamentPlajaControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TipEchipamentPlajaControllerApi', function() {
    describe('createTipEchipamentPlajaUsingPOST', function() {
      it('should call createTipEchipamentPlajaUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createTipEchipamentPlajaUsingPOST
        //instance.createTipEchipamentPlajaUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTipEchipamentPlajaUsingDELETE', function() {
      it('should call deleteTipEchipamentPlajaUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteTipEchipamentPlajaUsingDELETE
        //instance.deleteTipEchipamentPlajaUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllTipuriEchipamentePlajaUsingGET', function() {
      it('should call getAllTipuriEchipamentePlajaUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllTipuriEchipamentePlajaUsingGET
        //instance.getAllTipuriEchipamentePlajaUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTipEchipamentPlajaByIdUsingGET', function() {
      it('should call getTipEchipamentPlajaByIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getTipEchipamentPlajaByIdUsingGET
        //instance.getTipEchipamentPlajaByIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchTipEchipamentPlajaUsingPATCH', function() {
      it('should call patchTipEchipamentPlajaUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test patchTipEchipamentPlajaUsingPATCH
        //instance.patchTipEchipamentPlajaUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTipEchipamentPlajaUsingPUT', function() {
      it('should call updateTipEchipamentPlajaUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateTipEchipamentPlajaUsingPUT
        //instance.updateTipEchipamentPlajaUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
