/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import StareRezervare from '../model/StareRezervare';

/**
* StareRezervareController service.
* @module api/StareRezervareControllerApi
* @version 1.0
*/
export default class StareRezervareControllerApi {

    /**
    * Constructs a new StareRezervareControllerApi. 
    * @alias module:api/StareRezervareControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllStariRezervariUsingGET operation.
     * @callback module:api/StareRezervareControllerApi~getAllStariRezervariUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/StareRezervare>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllStariRezervari
     * @param {module:api/StareRezervareControllerApi~getAllStariRezervariUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/StareRezervare>}
     */
    getAllStariRezervariUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [StareRezervare];
      return this.apiClient.callApi(
        '/stari-rezervari', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
